#!/usr/bin/env python3
"""Generate a sprint retro report in Markdown.

Input:  { sprint_id: Text, kpis: Record, feedback_items: List<Record>,
          started_at: Text, ended_at: Text }
Output: { report_markdown: Text }

Pure stage (template-based).
"""


def execute(input: dict) -> dict:
    data = input
    sprint_id = data["sprint_id"]
    kpis = data.get("kpis", {})
    feedback = data.get("feedback_items", [])
    started = data.get("started_at", "")
    ended = data.get("ended_at", "")

    lines = []
    lines.append(f"# Sprint Retro — {sprint_id}\n")

    # Summary
    lines.append("## Summary\n")
    lines.append(f"- Total tasks: {kpis.get('total_tasks', 0)}")
    lines.append(f"- Completed: {kpis.get('completed_tasks', 0)}")
    lines.append(f"- Completion rate: {kpis.get('completion_rate', 0) * 100:.0f}%")
    lines.append(f"- Sprint duration: {kpis.get('sprint_days', 0):.1f} days")
    lines.append(f"- Velocity: {kpis.get('tasks_per_day', 0):.1f} tasks/day")
    lines.append(f"- Escalations: {kpis.get('escalated_count', 0)}")
    lines.append(f"- Avg interventions/task: {kpis.get('avg_interventions', 0):.1f}")
    lines.append("")

    # Feedback highlights
    parsed_feedback = [f for f in feedback if f.get("is_parsed_yaml") and f.get("parsed")]
    if parsed_feedback:
        lines.append("## Agent Feedback\n")
        for fb in parsed_feedback:
            p = fb["parsed"]
            lines.append(f"### {p.get('task_id', 'unknown')} ({p.get('agent_role', '')})\n")
            lines.append(f"- Clarity: {p.get('task_clarity', '?')}/10")
            lines.append(f"- Self-assessment: {p.get('self_assessment', '?')}")
            lines.append(f"- Tokens: {p.get('tokens_consumed', '?')}")
            lines.append(f"- Time: {p.get('time_to_complete_min', '?')} min")
            blockers = p.get("blockers", [])
            if blockers:
                lines.append("- Blockers:")
                for b in blockers:
                    lines.append(f"  - {b}")
            notes = p.get("notes")
            if notes:
                lines.append(f"- Notes: {notes}")
            lines.append("")

    # KPI table
    lines.append("## KPI Dashboard\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    for key, value in kpis.items():
        label = key.replace("_", " ").title()
        if isinstance(value, float):
            lines.append(f"| {label} | {value:.2f} |")
        else:
            lines.append(f"| {label} | {value} |")
    lines.append("")

    lines.append("---\n*Generated by Caloron Retro Engine (Noether)*")

    report = "\n".join(lines)
    return {"report_markdown": report}
